### ISSUE TITLE
Now all are "Undefined Spawns"

### ISSUE THREAD

**Issue by andyobryan** [davyvong/pokebot#3]

**Comment by HATB0T** [comment]
I also get Undefined when using this. Any known fix atm?

**Comment by Virg099** [comment]
no fix yet, pokecord changed the ids of the img i think

**Comment by HATB0T** [comment]
There is another bot that still works for catching, I might peek at their code and see what their workaround is.

**Comment by Virg099** [comment]
Well if you do find out, let davyvong know

**Comment by davyvong** [comment]
I am currently looking into alternatives and have considered hashing the images similar to xKynn's bot. I will try to fix this issue asap.

**Comment by davyvong** [comment]
I just pushed a commit (af08e9eab11294f8457ea5bfbdbfbf2e4370ab6f) to resolve this issue. Refreshing the demo website or pulling the latest commits will resolve the issue.
