### ISSUE TITLE
So the devs for pokecord broke the autocatchers

### ISSUE THREAD

**Issue by Virg099** [davyvong/pokebot#4]
The old pokemon image links used to be the following where we can determine the pokemon names from the id (VslAzbmfiGka=Paras)
(Paras) https://www.pokecord.com/assets/VslAzbmfiGka.png
But now they changed it to:
(Psyduck) https://cdn.discordapp.com/attachments/438855034491633664/445064276445626368/PokecordSpawn.jpg
This doesn't look good for bots since the bot is manually uploading images rather getting them from a link, not sure if the attachment ids will be the same every time.
However OCR bots may still be able to work pretty well (I do not know of any)

**Comment by Virg099** [comment]
On a side note, the spammer still works, which is great for lvling pokes

**Comment by davyvong** [comment]
Thanks for bringing this to my attention. I will post updates in issue #3.

**Comment by davyvong** [comment]
I just pushed a commit (af08e9eab11294f8457ea5bfbdbfbf2e4370ab6f) to resolve this issue.
