### ISSUE TITLE
Pokemon with Missing Images

### ISSUE THREAD

**Issue by davyvong** [davyvong/pokebot#5]
There are some Pokemon that that do not have images.

As a result, the Pokebot will not be able to catch the following:
- Chingling
- Hariyama
- Noivern

Please let me know if there are any other Pokemon with missing images or if Pokecord updates their bot to include any of the above mentioned Pokemon.

**Comment by Virg099** [comment]
Images have been updated, they exist now

**Comment by davyvong** [comment]
I have found some links for Chingling, Hariyama, and Noivern. They will be shortly added to the bot's master list.
https://media.discordapp.net/attachments/445311229020602388/446042250623844363/PokecordSpawn.jpg

**Comment by davyvong** [comment]
I pushed a commit (383ddbf5499ea17f6cbef9937039f43dda126f4f) to mitigate this issue.
