### ISSUE TITLE
image change

### ISSUE THREAD

**Issue by nharpa** [davyvong/pokebot#6]
Hi Davy,
FYI not long ago pokecord changed the images and in turn url's. So your lookup table it not longer valid. A quick look at 2 url's from the same mon on different server has me thinking they may now be salting. 
Keep up the good work

edit. just confirmed that 2 mons in same server with different url's

**Comment by davyvong** [comment]
Seems like they have resized all their images to a 240x240 format. As a result, all the hashes have changed and I am currently exploring into a methods to best handle the situation.

**Comment by andyobryan** [comment]
anything we could help with here?

**Comment by dragoon569** [comment]
so the catch function doesn't work ?

**Comment by davyvong** [comment]
The catch function does not work at the moment. I'm looking into client-sided image resizers to make comparisons with reference images to determine the Pokemon name.

**Comment by dragoon569** [comment]
Any advancements yet ?

**Comment by davyvong** [comment]
I don't think its possible to resolve this issue within the browser like my project does. I would suggest alternatives such as https://github.com/Hyperclaw79/PokeBall-SelfBot.

**Comment by dragoon569** [comment]
$25 dls for something like a mini game on discord
