### ISSUE TITLE
Dont Catch?

### ISSUE THREAD

**Issue by LightBlueYT** [davyvong/pokebot#8]
Hey ive tested the bot and it works fine with the spam just  it wont catch stuff automaticly

**Comment by LuhComZ** [comment]
same inssue

**Comment by davyvong** [comment]
This project is now out of date and currently does not have a workaround to identify Pokemon within the browser. I may make a bot in python or javascript (node) in the future but for now, I would suggest alternatives such as https://github.com/Hyperclaw79/PokeBall-SelfBot.
